version: "3"

services:
  app:
    build:
      context: ./
      target: app
    volumes:
      - ./data:/algomo/data
      - ./models:/algomo/models
    ports:
      - 5555:5555
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/opt/pipelines/pipelines.haystack-pipeline.yml
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      llm:
        condition: service_healthy

  llm:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure